{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hawklibraries",
    "module": "Hawk-Libraries",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2024.2.4"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "com.kauailabs.navx.frc",
          "module": "navx-frc-java",
          "version": {
            "requires": "2024.1.0"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2024.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "Hawk-Libraries-0.0.1.jar",
          "url": "Hawk-Libraries-0.0.1.jar",
          "size": 43268,
          "sha512": "afbc9c2bd399ef179e641eee8847e52ecfb411c27945dafe65cc8d56aa9588e1451d44591968ac31fdfbc5f95da2e72dea0bcb36bf9f35ecc34e0ecef6cb653b",
          "sha256": "68e1d699508ba7e22cb38ecd8c512cecab3e6d415e1027407707eeea81a7b9a7",
          "sha1": "e63e0ceabbfdfd5b5df88fe6fb5ed497874cb313",
          "md5": "5c3f0a158fd0231aaa893464f1bbfaa4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2024.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.8.0-2"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2024.2.4"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "com.kauailabs.navx.frc",
          "module": "navx-frc-java",
          "version": {
            "requires": "2024.1.0"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2024.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "Hawk-Libraries-0.0.1.jar",
          "url": "Hawk-Libraries-0.0.1.jar",
          "size": 43268,
          "sha512": "afbc9c2bd399ef179e641eee8847e52ecfb411c27945dafe65cc8d56aa9588e1451d44591968ac31fdfbc5f95da2e72dea0bcb36bf9f35ecc34e0ecef6cb653b",
          "sha256": "68e1d699508ba7e22cb38ecd8c512cecab3e6d415e1027407707eeea81a7b9a7",
          "sha1": "e63e0ceabbfdfd5b5df88fe6fb5ed497874cb313",
          "md5": "5c3f0a158fd0231aaa893464f1bbfaa4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Hawk-Libraries-0.0.1-sources.jar",
          "url": "Hawk-Libraries-0.0.1-sources.jar",
          "size": 13543,
          "sha512": "b782429eba681db6393a14eebc94e610e28dfda5fce89d9e529ddbfaeb410e506a87f490f0b046796209e26e0a1609eef2862c4ca0bb14a33a8b85d0cf28f5cf",
          "sha256": "edf01e26504a080cd58293839c59055f52431b019bc5f0d020771f7dc800bc68",
          "sha1": "3c1b7643ac618a8aa255a1913c87e4c6f60d0d94",
          "md5": "c049c048a8189fe72b19ac63531f26ad"
        }
      ]
    }
  ]
}
