{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hawklibraries",
    "module": "Hawk-Libraries",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2024.2.4"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "com.kauailabs.navx.frc",
          "module": "navx-frc-java",
          "version": {
            "requires": "2024.1.0"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2024.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "Hawk-Libraries-0.0.1.jar",
          "url": "Hawk-Libraries-0.0.1.jar",
          "size": 43268,
          "sha512": "1e20863d7ec19d924b3723f85dfc8de8d66743314dd8d8159058bf157039e89462153ec99fc21142168a427867f9aab39ec38ffdcea05491c4e2a20b85e7efc0",
          "sha256": "53af5910d77aaa6cccc50f25620912ad5ee28c0220ca84659d95b8f5533df710",
          "sha1": "ae33cc4552c1ad05c94e32c1e8e146ecb751f618",
          "md5": "6bcc00ae75651597a0a3cb7f24547d7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2024.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.8.0-2"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2024.2.4"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "com.kauailabs.navx.frc",
          "module": "navx-frc-java",
          "version": {
            "requires": "2024.1.0"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2024.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "Hawk-Libraries-0.0.1.jar",
          "url": "Hawk-Libraries-0.0.1.jar",
          "size": 43268,
          "sha512": "1e20863d7ec19d924b3723f85dfc8de8d66743314dd8d8159058bf157039e89462153ec99fc21142168a427867f9aab39ec38ffdcea05491c4e2a20b85e7efc0",
          "sha256": "53af5910d77aaa6cccc50f25620912ad5ee28c0220ca84659d95b8f5533df710",
          "sha1": "ae33cc4552c1ad05c94e32c1e8e146ecb751f618",
          "md5": "6bcc00ae75651597a0a3cb7f24547d7a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Hawk-Libraries-0.0.1-sources.jar",
          "url": "Hawk-Libraries-0.0.1-sources.jar",
          "size": 13543,
          "sha512": "8dba010f58c5bd9517ed21ed6d0c924fc4833af23244fa1a8121c7d70a14a67678bd90840e0c9485856f163390c1a181e658c5748f40f9963e7502e94755c356",
          "sha256": "8f1c928dd489857d6b44f0a5db3f4f9e90e6e70dc1e0e1b28bb3634ff1eac92b",
          "sha1": "c3329f8f2ee7c6d6b6fee0f86e253675090bdcac",
          "md5": "7c6cc3a267414453dfff3f6e76538bbf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Hawk-Libraries-0.0.1-javadoc.jar",
          "url": "Hawk-Libraries-0.0.1-javadoc.jar",
          "size": 140719,
          "sha512": "03e2da2b42471c3732f0cafca3afb6920930265624cb870faecdc51c71f0a58538eec67801634e1deb6f185c00fa66f7dc2f49e7ef933f94933a6d40d60555f2",
          "sha256": "c5806c0f01f79dfa2ca093fc241dfc4dde3011f1b79ddacbe4556cc17996eab7",
          "sha1": "b7cf0544ec6bac63edd355616f36bdfbf1791b59",
          "md5": "e2a2c2e391571c5482dde0261e770277"
        }
      ]
    }
  ]
}
