{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hawklibraries",
    "module": "Hawk-Libraries",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2024.2.4"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "com.kauailabs.navx.frc",
          "module": "navx-frc-java",
          "version": {
            "requires": "2024.1.0"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2024.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "Hawk-Libraries-0.0.1.jar",
          "url": "Hawk-Libraries-0.0.1.jar",
          "size": 43544,
          "sha512": "363262d281b9019f0feb93b3f5ef455a3f2f5d0a8e26e20b687c17817f9fd262c63087fbe89f25584d36a0ebe8ff8023ba1c5eff81035243f787661a1ccaa7a1",
          "sha256": "fdf6c598e51906ee459b2133ae7be38025f83b8248a8171f32be324b11960eca",
          "sha1": "e98c06e23b6d7ba785bd97e91e8188a659745144",
          "md5": "70ce4de6361081bf4335755564863a67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2024.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.8.0-2"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2024.2.4"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "24.3.0"
          }
        },
        {
          "group": "com.kauailabs.navx.frc",
          "module": "navx-frc-java",
          "version": {
            "requires": "2024.1.0"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2024.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "Hawk-Libraries-0.0.1.jar",
          "url": "Hawk-Libraries-0.0.1.jar",
          "size": 43544,
          "sha512": "363262d281b9019f0feb93b3f5ef455a3f2f5d0a8e26e20b687c17817f9fd262c63087fbe89f25584d36a0ebe8ff8023ba1c5eff81035243f787661a1ccaa7a1",
          "sha256": "fdf6c598e51906ee459b2133ae7be38025f83b8248a8171f32be324b11960eca",
          "sha1": "e98c06e23b6d7ba785bd97e91e8188a659745144",
          "md5": "70ce4de6361081bf4335755564863a67"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Hawk-Libraries-0.0.1-sources.jar",
          "url": "Hawk-Libraries-0.0.1-sources.jar",
          "size": 15657,
          "sha512": "a2fb352dff267bd4f2fcb960d74b336d6c5ce7164eb14ba2c5033b8587132d48718cf401de64ddd466e54de7ed80ff0ff194a17f966cc33751b31dfbbc6f8343",
          "sha256": "4d980b0b7f35edc1441a5cf5a1a1065fcd6675d38cc9707457a31e3345d1e44b",
          "sha1": "4f028cb214ba5f3fefe631b2b2baa1a0be0b05b4",
          "md5": "633d5e7a1fdb2db70ae0d7c818398df0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Hawk-Libraries-0.0.1-javadoc.jar",
          "url": "Hawk-Libraries-0.0.1-javadoc.jar",
          "size": 142273,
          "sha512": "db3f1be23f4df481668d91ded13d135a731f053228b53e3c3b2950f9e54316548733a49d193059f40625d8cbd47457e50d6d530e9ea4486346f53f88bc306257",
          "sha256": "567531a6b16eae67e91750ab4db70281a1b888f8983d66f6b03c96febcae1c04",
          "sha1": "2c95e906ecee708526b0a8a818944d19600416e1",
          "md5": "0617dd6530d8a51e35e41d8643e81a00"
        }
      ]
    }
  ]
}
