{
  "formatVersion": "1.1",
  "component": {
    "group": "frc.hawklibraries",
    "module": "hawklibraries",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hawklibraries-0.0.1.jar",
          "url": "hawklibraries-0.0.1.jar",
          "size": 6712613,
          "sha512": "e266a62ba3bd7088bc7413a4e3579d0f29ebb94725d0d2672e097526d9007025d13a52a777130e7d7d18d61440737a538fd41e51d7813783359de9dbde68664d",
          "sha256": "f5a8a6aad9e6b038f792d770ace7b76b4b8ef19f781b6806d6445dc26d65526c",
          "sha1": "5874dae8df667c10dc0daaa1ae1871459b3e4315",
          "md5": "c277bff482ec4755a1ef46aa8985e8ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2024.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.8.0-2"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2024.2.8"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2024.2.4"
          }
        },
        {
          "group": "com.kauailabs.navx.frc",
          "module": "navx-frc-java",
          "version": {
            "requires": "2024.1.0"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "24.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "hawklibraries-0.0.1.jar",
          "url": "hawklibraries-0.0.1.jar",
          "size": 6712613,
          "sha512": "e266a62ba3bd7088bc7413a4e3579d0f29ebb94725d0d2672e097526d9007025d13a52a777130e7d7d18d61440737a538fd41e51d7813783359de9dbde68664d",
          "sha256": "f5a8a6aad9e6b038f792d770ace7b76b4b8ef19f781b6806d6445dc26d65526c",
          "sha1": "5874dae8df667c10dc0daaa1ae1871459b3e4315",
          "md5": "c277bff482ec4755a1ef46aa8985e8ba"
        }
      ]
    }
  ]
}
