{
  "formatVersion": "1.1",
  "component": {
    "group": "frc.hawklibraries",
    "module": "hawklibraries",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hawklibraries-0.0.1.jar",
          "url": "hawklibraries-0.0.1.jar",
          "size": 6712613,
          "sha512": "fce903213d711814cb5c9eb0487776cc7e0712e2868dce5859d95f110de10c78265bb9958c3c00e8a6346e6cdad10b867094e0caac671d3cadc9d46c61ffddd8",
          "sha256": "7f896d018b4835a72e2743345afd6e69e3212b0ca80c20abbca3cb73e97232d3",
          "sha1": "5972a36c5c141e576a59f1627fada5d46d2444be",
          "md5": "2ff6902afb45aa25b10819e10f3c47c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2024.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.8.0-2"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2024.2.8"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2024.2.4"
          }
        },
        {
          "group": "com.kauailabs.navx.frc",
          "module": "navx-frc-java",
          "version": {
            "requires": "2024.1.0"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "24.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "hawklibraries-0.0.1.jar",
          "url": "hawklibraries-0.0.1.jar",
          "size": 6712613,
          "sha512": "fce903213d711814cb5c9eb0487776cc7e0712e2868dce5859d95f110de10c78265bb9958c3c00e8a6346e6cdad10b867094e0caac671d3cadc9d46c61ffddd8",
          "sha256": "7f896d018b4835a72e2743345afd6e69e3212b0ca80c20abbca3cb73e97232d3",
          "sha1": "5972a36c5c141e576a59f1627fada5d46d2444be",
          "md5": "2ff6902afb45aa25b10819e10f3c47c3"
        }
      ]
    }
  ]
}
